[Option B] Sirouk patch synth avatar
rayonlabs/nineteen pull request #59
Opened 2024-10-12 04:09 UTC by sirouk

2024-10-14 09:11 UTC, rumayao approved these changes

2024-10-15 11:14 UTC, tripathiarpan20 commented
Looks good other than a single line

2024-10-15 11:18 UTC, tripathiarpan20 requested changes

2024-10-15 11:18 UTC, tripathiarpan20 commented on miner/endpoints/image.py
> +        model_name = task_config.orchestrator_server_config.load_model_config["model"]
`if "model" in task_config.orchestrator_server_config.load_model_config:` , otherwise looks good

2025-04-28 17:03 UTC, closed without merging